### ISSUE TITLE
Any plans to include a DRM example?

### ISSUE THREAD

**Issue by fariazz** [Azure-Samples/media-services-v3-node-tutorials#1]
The .NET repo has a DRM example, it would be amazing if you could include one for Node.js as well: https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials/tree/master/AMSV3Tutorials/EncryptWithDRM

I've struggled for days to get a simple Widevine demo to work (we are developing an app that will allow offline video viewing) and I've been hitting wall after wall. Even a simple example would go a long way.

**Comment by johndeu** [comment]
Added an updated streaming with DRM sample to the repo for the newer SDK.
