### ISSUE TITLE
Streaming DRM video in a player

### ISSUE THREAD

**Issue by orizvida** [Azure-Samples/media-services-v3-node-tutorials#19]
Hi,
First of all thank you very much for this repository, it is very useful and clear.

I have an issue that is not covered in here and I think would be great if we will have some reference to it since I am searching the solution for days now.

After uploading DRM video and recieving back the URL and token as the following:
https://name-euwe.streaming.media.azure.net/{{Guid}}/AzurePromo.ism/manifest(encryption=cenc)
and a JWT token I need to stream it in a video player like videojs or so but I can't figure out how to pass the token.
When using the https://ampdemo.azureedge.net/ it works great but on every other way I try to pass the token I don't get the desired video, Tried to pass the token with this repo as well with not result https://github.com/Azure-Samples/media-services-3rdparty-player-samples/tree/master/src/video.js,
Do we need a Widevine license URL or something else?

Thank you!

**Comment by johndeu** [comment]
@orizvida  - I missed this issue back in December. Did you get this working correctly on your service? 

Some of the 3rd party players do not support Widevine without explicitly setting the license URL in the actual player itself.  I think Video.js had that issue where it was not reading the license URL from the manifest and needs it to be set explicitly.

**Comment by johndeu** [comment]
Closing this as an external issue. Let me know if you need more support on this @orizvida
