### ISSUE TITLE
Use Media Services to deliver DRM licenses

### ISSUE THREAD

**Issue by xedsvg** [Azure-Samples/media-services-v3-node-tutorials#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create a content key with the new v3 and try to get the delivery url

### Any log messages given by the failure
> --

### Expected/desired behavior
> Have a way to get the Delivery URL as in v2 [(Get Delivery URL v2)](https://docs.microsoft.com/en-us/rest/api/media/operations/contentkey#get_delivery_service_url)

### OS and Version?
> Any platform

### Versions
> MediaServices v3

### Mention any other details that might be useful

Is there any way to migrate to v3 and [only deliver DRM licenses](https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-deliver-keys-and-licenses)? We have a on premise server for our files and would like to migrate to v3. We searched the whole project for any hints that may help us but with no luck.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
No that scenario is not fully supported in V3.  We require that you stream the content with encryption through the AMS services today.  V2 API will also be deprecated soon.
