### ISSUE TITLE
Error when running build command

### ISSUE THREAD

**Issue by wwalmnes** [Azure-Samples/media-services-v3-node-tutorials#20]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> `npm i`
> `npm run build`

### Any log messages given by the failure
 ```
> media-services-node-sample@0.2.0 build
> build:tsc

sh: 1: build:tsc: not found
```

### Expected/desired behavior
> Able to build the project

### OS and Version?
> Ubuntu 18.04.6

### Versions
>

### Mention any other details that might be useful
This can be fixed by changing the `build` script in `package.json` from `build:tsc` to `npm run build:tsc` 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
Also good catch, thanks William
