### ISSUE TITLE
Cannot compile typescript

### ISSUE THREAD

**Issue by wwalmnes** [Azure-Samples/media-services-v3-node-tutorials#21]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> `npm i`
> `npm run build`

### Any log messages given by the failure
```
> media-services-node-sample@0.2.0 build
> npm run build:tsc


> media-services-node-sample@0.2.0 build:tsc
> tsc -p ./tsconfig.json

StreamFilesSample/index.ts:17:27 - error TS2307: Cannot find module '../Common/Encoding/TransformFactory' or its corresponding type declarations.

17 import * as factory  from "../Common/Encoding/TransformFactory";
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in StreamFilesSample/index.ts:17
```

### Expected/desired behavior
> Being able to compile typescript.

### OS and Version?
> Ubuntu 18.04

### Versions
>

### Mention any other details that might be useful
*NOTE*: Assumes the fix for https://github.com/Azure-Samples/media-services-v3-node-tutorials/issues/20 is implemented in order to run the `npm run build` command. 

This can be fixed by fixing the casing for the imports. The file is named `transformFactory.ts` and the imports should be `../Common/Encoding/transformFactory`.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
Got this one, thank you William!
