### ISSUE TITLE
Any plans to migrate the example from azure-sdk-for-node to azure-sdk-for-js?

### ISSUE THREAD

**Issue by tanyaYourchuck** [Azure-Samples/media-services-v3-node-tutorials#3]
Just wondering since there is note on the `azure-arm-mediaservices` module:
**This SDK will be deprecated next year and will be replaced by a new TypeScript-based isomorphic SDK (found at https://www.npmjs.com/package/@azure/arm-mediaservices) which works on Node.js and browsers. See https://aka.ms/azure-sdk-for-js-migration to learn more.**

**Comment by alexsignly** [comment]
I'm with you @tanyaYourchuck. I'd really like to have these examples using azure-sdk-for-js, specially because of the azure blob service.

**Comment by ramya-rao-a** [comment]
Thanks for reporting folks!

@johndeu is working on updating the sample in the branch [updatedNodeSDK](https://github.com/Azure-Samples/media-services-v3-node-tutorials/tree/updatedNodeSDK).

@johndeu, Please close this issue once the samples are updated

**Comment by johndeu** [comment]
yes, working (slowly) on updating the samples in the branch noted above. Let me know if you would like to help.

**Comment by johndeu** [comment]
You can see the first 3 samples, Hello world, StreamFilesSample and StreamFilesWithDRMSample.  Those are working
I need red-do the Video Indexer Sample still, and add ones for Live Streaming.
See if the StreamFilesSample in that branch works for you and suggestions welcome, as I'm not a pro Node.js coder or Typescript dev at all.

**Comment by johndeu** [comment]
I finished this today - merged into Main. 

Added a LIve streaming sample.. Could use more folks to code review.
